// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ViewModelnapraven : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ViewModelnapraven));
        
        string IMigrationMetadata.Id
        {
            get { return "202001261655520_ViewModel napraven"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
